kind: pipeline
name: default

type: docker
workspace:
  base: /go
  path: src/github.com/markelrep/spendshelf-backend
steps:
  - name: test
    image: golang
    commands:
      - cd src/
      - go mod tidy
      - go test ./tests/
      - go build