kind: pipeline
name: default

type: docker
workspace:
  base: /go
  path: src/github.com/markelrep/spendshelf-backend/src
steps:
  - name: test
    image: golang
    commands:
      - go mod tidy
      - go test ./tests/
      - go build